### ISSUE TITLE
Your Mod does not work with MemoryLeakFix

### ISSUE THREAD

**Issue by Cixon** [AbdElAziz333/Saturn#10]
Specific Version:
https://www.curseforge.com/minecraft/mc-mods/memoryleakfix/files/4465268

Log:
[latest.log](https://github.com/AbdElAziz333/Saturn/files/11513695/latest.log)

Context:
I tried to get your mod to load on my modpack but sadly, it keeps trying to redirect mixins around which freezes the client start-up phase..

**Comment by border999** [comment]
same issue

**Comment by theshadowake** [comment]
Latest version has a mixin conflict as others have stated. Means I can't update my mod packs version of Saturn. An update with a fix would be appreciated.

**Comment by WolfBV** [comment]
https://github.com/fxmorin/MemoryLeakFix/issues/115
