### ISSUE TITLE
1.20/1.20.1 support

### ISSUE THREAD

**Issue by xfk97** [AbdElAziz333/Saturn#12]

**Comment by Emil2010** [comment]
AbdElAziz333 is out of modding again

**Comment by AbdElAziz333** [comment]
1.20/1.20.1 will come soon with new optimizations.

**Comment by rainysux** [comment]
@AbdElAziz333 is the build in your github useable? :)

**Comment by AbdElAziz333** [comment]
1.20.1/1.20.2 updates are available, good luck.
