### ISSUE TITLE
crashing repeatedly with error code 1 with newest version

### ISSUE THREAD

**Issue by hi4444** [AbdElAziz333/Saturn#13]
I send the modpack im using the 3 mods at top for create cant be updated or crashs and your mod will crash when launching with the newest https://drive.google.com/file/d/1PDpdsvr0lFDZIbkJExJou3jwt3Yi_BdO/view?usp=drive_link file was to big due to kubejs recipes so had to put drive link with file

**Comment by AbdElAziz333** [comment]
after some testing, everything works good, are you sure the issue is not from the launcher itself ?

**Comment by hi4444** [comment]
> after some testing, everything works good, are you sure the issue is not from the launcher itself ?

not the launcher it only happens when i update the mod to most recent version it works fine with prevoius

**Comment by Raft08** [comment]
I get the same issue here I will just simply add my mod list @hi4444 if you can send your mod list so we can compare which mods we have in commons it may be useful to filter the mods we have in common.

[Async Locator (by bright_spark)](https://www.curseforge.com/minecraft/mc-mods/async-locator)
    [Oculus Particle Fix (by LaidBackSloth)](https://www.curseforge.com/minecraft/mc-mods/oculus-particle-fix)
    [FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
    [YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
    [Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
    [Dynamic Trees - Tectonic (by djs_minecraft)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-tectonic)
    [YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
    [Ksyxis (by VidTu)](https://www.curseforge.com/minecraft/mc-mods/ksyxis)
    [Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
    [FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
    [Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
    [End's Phantasm (by Lyof429)](https://www.curseforge.com/minecraft/mc-mods/phantasm)
    [Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
    [Client Crafting (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
    [Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
    [Electrodynamics (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/electrodynamics)
    [Reliquary Reincarnations (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations)
    [FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
    [Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
    [Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Adaptive Performance Tweaks: Player Login Optimization and Protection (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-player)
    [Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
    [Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
    [Connectedness (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/connectedness)
    [Thermal Integration (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-integration)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
    [YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
    [Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
    [FixMySpawnR (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/fixmyspawnr)
    [Recipe Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric)
    [When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
    [Cataclysm Weaponery (by eyezlevrai)](https://www.curseforge.com/minecraft/mc-mods/cataclysmweaponery)
    [Mekanism-MoreSolarPanels (by Pocky)](https://www.curseforge.com/minecraft/mc-mods/mekanism-moresolarpanels)
    [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
    [YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [End Remastered (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/endremastered)
    [Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [TexTrue's Embeddium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)
    [Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
    [Mahou Tsukai (by stepcros)](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)
    [Lightspeed - Launch optimizations (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)
    [Ballistix (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/ballistix)
    [CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
    [Thermal Innovation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
    [More Mekanism Processing (by 지젤쟝다)](https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing)
    [fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
    [Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
    [YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
    [Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
    [Client Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks)
    [MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
    [The Aether: Redux (by Zepalesque)](https://www.curseforge.com/minecraft/mc-mods/aether-redux)
    [Adaptive Performance Tweaks: Items (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-items)
    [YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
    [Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
    [FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
    [EE: Thermal Expansion (by Ridanisaurus)](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica-thermal-addon)
    [Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
    [Emendatus Enigmatica (by Ridanisaurus)](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica)
    [Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
    [Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
    [Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
    [Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
    [Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
    [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
    [Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
    [Adaptive Performance Tweaks: Gamerules (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-gamerules)
    [Dynamic Trees + (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamictreesplus)
    [Adaptive Performance Tweaks: Core (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core)
    [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
    [CC: BallistiX (by TheThotSlayerTSC)](https://www.curseforge.com/minecraft/mc-mods/cc-ballistx)
    [Dynamic Trees (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)
    [EE: Create (by Ridanisaurus)](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica-create-addon)
    [Nullscape (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/nullscape)
    [Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
    [Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
    [Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
    [JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
    [Dynamic Trees - Biomes O' Plenty (by cadaverous_queen)](https://www.curseforge.com/minecraft/mc-mods/dtbop)
    [Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
    [EE: Mekanism (by Ridanisaurus)](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica-mekanism-addon)
    [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
    [Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
    [Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
    [AeroBlender (by TeamRazor)](https://www.curseforge.com/minecraft/mc-mods/aeroblender)
    [Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
    [YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
    [Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
    [Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
    [Divine Weaponry - Better Combat (by WoroxIV)](https://www.curseforge.com/minecraft/mc-mods/divine-weaponry)
    [Redirector [Modern] (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/redirectionor)
    [MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
    [YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
    [Reforgium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/reforgium)
    [Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
    [BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
    [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
    [Fast Paintings (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/fast-paintings)
    [Dynamic Trees - Quark (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark)
    [Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
    [Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
    [The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
    [CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
    [Sodium/Rubidium Occlusion Culling Fix (by yezhiyi)](https://www.curseforge.com/minecraft/mc-mods/sodium-rubidium-occlusion-culling-fix)
    [Inventory Pets (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/inventory-pets)
    [Tectonic (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/tectonic)
    [The Aether (by TheAetherTeam)](https://www.curseforge.com/minecraft/mc-mods/aether)
    [Suggestion Provider Fix (by HarleyOConnor)](https://www.curseforge.com/minecraft/mc-mods/suggestion-provider-fix)
    [Adaptive Performance Tweaks: Mods (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-mods)
    [Thermal Endergy (by EpicSquid315)](https://www.curseforge.com/minecraft/mc-mods/thermal-endergy)
    [Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
    [Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
    [Jade Addons (Forge) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
    [FTB Quests (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
    [FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
    [Let Me Despawn (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
    [Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
    [It Shall Not Tick (ISNT) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick)
    [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
    [JourneyMap Integration (by frankv_)](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration)
    [Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
    [Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
    [Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
    [Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
    [playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
    [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
    [Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
    [Structory: Towers (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory-towers)
    [L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
    [Mekanism-Evolution (by Pocky)](https://www.curseforge.com/minecraft/mc-mods/mekanism-evolution)
    [Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
    [Valhelsia Structures (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)
    [Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
    [Valhelsia Furniture (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-furniture)
    [Thermal Cultivation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
    [Waystones Teleport Pets (by precisemodpacker)](https://www.curseforge.com/minecraft/mc-mods/waystones-teleport-pets)
    [FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
    [Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
    [Better Rubidium Video Settings Button (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/brvsb)
    [Industrial Agriculture (by ArrowsendGaming)](https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture)
    [ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
    [Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
    [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
    [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
    [Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
    [Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
    [Magnesium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
    [Incendium (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/incendium)
    [Dynamic Trees - Terralith (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-terralith)
    [Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
    [AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
    [Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
    [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
    [YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
    [CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
    [Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
    [CCTV Craft (by NorthWestTreesGaming)](https://www.curseforge.com/minecraft/mc-mods/cctv-craft)
    [ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
    [CorgiLib (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/corgilib)
    [CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
    [Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
    [Create Big Cannons (by rbasamoyai)](https://www.curseforge.com/minecraft/mc-mods/create-big-cannons)
    [Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
    [Tectonic + Biomes O' Plenty compat (by djs_minecraft)](https://www.curseforge.com/minecraft/mc-mods/tectonic-bop)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Explorify – Dungeons & Structures (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/explorify)
    [Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
    [Mystical Agradditions (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions)
    [Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
    [ForgetMeChunk (Forge) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge)
    [Memory Usage Screen [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/memory-usage-screen)
    [Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
    [Thermal Dynamics (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
    [Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
    [FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
    [Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
    [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
    [MemorySweep (by Tki_sor)](https://www.curseforge.com/minecraft/mc-mods/memorysweep)

**Comment by AbdElAziz333** [comment]
Can you please use the new update?
[1.18.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.18.2-0.0.6) - [1.19.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.2-0.0.6) - [1.19.3](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.3-0.0.6) - [1.19.4](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.4-0.0.6) - [1.20.1](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.1-0.0.6) - [1.20.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.2-0.0.6)

**Comment by Raft08** [comment]
Can confirm, update fixes this issue thx!
