### ISSUE TITLE
1.18.2 latest disables swimming?! Also, underwater render distance is ridiculous all the sudden.

### ISSUE THREAD

**Issue by GordonRamsay20** [AbdElAziz333/Saturn#14]
After updating I can't swim or use fast creative flight underwater, even tho I can above water idk if this is Saturn but it only happened after updating. I can only see like 5 feet in front of me underwater, this update broke stuff idk

**Comment by GordonRamsay20** [comment]
Downgrading to 0.0.4 fixed all these issues

**Comment by AbdElAziz333** [comment]
What other mods you are using with Saturn? i tested with Saturn only and everything works good.

**Comment by GordonRamsay20** [comment]
Mods on Server: ```hexerei-0.2.2.jar                                 |Hexerei                       |hexerei                       |0.2.2               |DONE      |Manifest: NOSIGNATURE
		saturn-mc1.18.2-0.0.4.jar                         |Saturn                        |saturn                        |0.0.5               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0.1  |DONE      |Manifest: NOSIGNATURE
		netherportalfix-forge-1.18.2-9.0.1.jar            |NetherPortalFix               |netherportalfix               |9.0.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.18.2-Forge-1.0.3  |DONE      |Manifest: NOSIGNATURE
		connectivity-1.18.2-3.2.jar                       |Connectivity Mod              |connectivity                  |1.18.2-3.2          |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.0-mc1.18.2forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.0               |DONE      |Manifest: NOSIGNATURE
		etched-forge-2.2.1+1.18.2.jar                     |Etched                        |etched                        |2.2.1               |DONE      |Manifest: NOSIGNATURE
		CTM-1.18.2-1.1.5+5.jar                            |ConnectedTexturesMod          |ctm                           |1.18.2-1.1.5+5      |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.9.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.9  |DONE      |Manifest: NOSIGNATURE
		LightlyColoredSeaLanterns-1.18.1-1.0.jar          |Lightly Colored Sea Lanterns  |lcsl                          |1.0.0               |DONE      |Manifest: NOSIGNATURE
		secretrooms-1.18.2-1.1.5.jar                      |Secret Rooms 6                |secretroomsmod                |1.18.2-1.1.5        |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.18.2.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		mermod-forge-1.01.jar                             |Mermod                        |mermod                        |1.01                |DONE      |Manifest: NOSIGNATURE
		fakename-1.18.1-1.3.5.jar                         |Fakename                      |fakename                      |1.3.5               |DONE      |Manifest: NOSIGNATURE
		balm-3.2.6.jar                                    |Balm                          |balm                          |3.2.6               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		good_grief-1.0.1.jar                              |Example Mod                   |good_grief                    |1.0.1               |DONE      |Manifest: NOSIGNATURE
		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.18.2-2.0.1.jar                    |Chipped                       |chipped                       |2.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.1.0-mc1.18.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		curious-armor-stands-1.18.1-4.0.1.jar             |Curious Armor Stands          |curious_armor_stands          |1.18.1-4.0.1        |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.1-mc1.18.2forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.18.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.18.2-Forge-2.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		fairylights-5.0.0-1.18.2.jar                      |Fairy Lights                  |fairylights                   |5.0.0               |DONE      |Manifest: NOSIGNATURE
		EyesInTheDarkness-1.18.2-1.2.7.jar                |Eyes in the Darkness          |eyesinthedarkness             |1.2.7               |DONE      |Manifest: NOSIGNATURE
		spark-1.10.38-forge.jar                           |spark                         |spark                         |1.10.38             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.1      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		arsomega-2.7.4.jar                                |Ars Omega                     |arsomega                      |1.18.2-2.7.4        |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.18.2-Forge-2.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		AngelRing2-1.18.2-2.0.4.jar                       |Angel Ring 2                  |angelring                     |2.0.4               |DONE      |Manifest: NOSIGNATURE
		bettervillage-forge-1.18.2-3.2.0.jar              |Better village                |bettervillage                 |3.2.0               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		pluto-mc1.18.2-0.0.6.jar                          |Pluto                         |pluto                         |0.0.6               |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.4-mc1.18.2forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.4               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre35-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre35         |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.0-mc1.18.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.0               |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.18.2-forge-2.5.0.jar                 |Jade Addons                   |jadeaddons                    |2.5.0               |DONE      |Manifest: NOSIGNATURE
		inventoryessentials-forge-1.18.2-4.0.3.jar        |Inventory Essentials          |inventoryessentials           |4.0.3               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.18.2forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		inventorysorter-1.18.2-19.0.4.jar                 |Simple Inventory Sorter       |inventorysorter               |19.0.4              |DONE      |Manifest: NOSIGNATURE
		jmi-forge-1.18.2-0.13-43.jar                      |JourneyMap Integration        |jmi                           |0.13-43             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.11-build.177.jar         |FTB Library                   |ftblibrary                    |1802.3.11-build.177 |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.11-build.107.jar           |FTB Teams                     |ftbteams                      |1802.2.11-build.107 |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.4.9+1.18.2-universal.jar  |Minecraft Comes Alive         |mca                           |7.4.9+1.18.2        |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v3.3.0-1.18.2-Forge.jar                 |Easy Magic                    |easymagic                     |3.3.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.2-forge-10.2.1.1005.jar                  |Just Enough Items             |jei                           |10.2.1.1005         |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.7.8+1.18.2-forge.jar                     |Pehkui                        |pehkui                        |3.7.8+1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.18.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.2.1.jar                 |Waystones                     |waystones                     |10.2.1              |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.4-mc1.18.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.18.2-7.1.41.jar               |Traveler's Backpack           |travelersbackpack             |7.1.43              |DONE      |Manifest: NOSIGNATURE
		lightmanscurrency-1.18.2-2.1.2.3a.jar             |Lightman's Currency           |lightmanscurrency             |1.18.2-2.1.2.3a     |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.18.1-2.2.3.jar                     |Guide-API VP                  |guideapi_vp                   |2.2.3               |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |DONE      |Manifest: NOSIGNATURE
		everycomp-1.18.2-1.6.4.jar                        |Every Compat                  |everycomp                     |1.18.2-1.6.4        |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.3.1  |DONE      |Manifest: NOSIGNATURE
		mahoutsukai-1.18.2-v1.34.57.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.18.2-v1.34.57     |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.12-1.18.2.jar                      |Ice and Fire                  |iceandfire                    |2.1.12-1.18.2       |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		boatload-1.18.2-3.0.0.jar                         |Boatload                      |boatload                      |3.0.0               |DONE      |Manifest: NOSIGNATURE
		environmental-1.18.2-2.0.0.jar                    |Environmental                 |environmental                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.1.jar                |Savage & Ravage               |savage_and_ravage             |4.0.1               |DONE      |Manifest: NOSIGNATURE
		woodworks-1.18.2-1.2.1.jar                        |Woodworks                     |woodworks                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.18.2-4.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |4.0.0               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.18.2-5.0.0.jar                       |Berry Good                    |berry_good                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.9.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.9.0               |DONE      |Manifest: NOSIGNATURE
		ars_scalaes-1.18.2-1.8.1-rework.jar               |Ars Nouveau Scaling Compats   |ars_scalaes                   |1.18.2-1.8.1-rework |DONE      |Manifest: NOSIGNATURE
		toomanyglyphs-1.18.1-2.0.7.15321.jar              |Too Many Glyphs               |toomanyglyphs                 |2.0.7.15321         |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1802.3.17-build.265.jar          |FTB Chunks                    |ftbchunks                     |1802.3.17-build.265 |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.9-universal.jar                 |Forge                         |forge                         |40.2.9              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TravelersTitles-1.18.2-Forge-2.1.1.jar            |Traveler's Titles             |travelerstitles               |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		toofast-1.18-0.0.1.3.jar                          |Too Fast                      |toofast                       |0.0.1.2             |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.18.2-3.0.0.jar                       |Neapolitan                    |neapolitan                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		mcw-paths-1.0.3forge-mc1.18.2.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.3               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.14.jar                         |Selene                        |selene                        |1.18.2-1.17.14      |DONE      |Manifest: NOSIGNATURE
		advancementframes-1.18.2-1.1.1.jar                |Advancement Frames            |advancementframes             |1.18.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.18.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.18       |DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		right_click_get_crops-1.18.2-1.4.0.10.jar         |Right Click, Get Crops        |right_click_get_crops         |1.4.0.10            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		upgrade_aquatic-1.18.2-4.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |4.0.0               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		pollen-forge-1.6.1+1.18.2.jar                     |Pollen                        |pollen                        |1.6.1               |DONE      |Manifest: NOSIGNATURE
		EasierSleeping-1.18.2-2.1.0.jar                   |Easier Sleeping               |easier_sleeping               |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.3.0.jar                       |Jade                          |jade                          |5.3.0               |DONE      |Manifest: NOSIGNATURE
		ArmorPoser-forge-1.18.2-1.0.5.jar                 |Armor Poser                   |armorposer                    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		another_furniture-forge-1.2.2-1.18.2.jar          |Another Furniture             |another_furniture             |1.2.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
		smoothboot(reloaded)-mc1.18.2-0.0.2.jar           |Smooth Boot (Reloaded)        |smoothboot                    |0.0.2               |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		DecorationDelightRefurbished-1.18.2.jar           |Decoration Delight            |decoration_delight            |1.0.0               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.49.jar                   |Polymorph                     |polymorph                     |1.18.2-0.49         |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.18.2-3.0.2.jar                |Abnormals Delight             |abnormals_delight             |3.0.2               |DONE      |Manifest: NOSIGNATURE
		[1.18.2] SecurityCraft v1.9.7.jar                 |SecurityCraft                 |securitycraft                 |1.9.8              |DONE      |Manifest: NOSIGNATURE
		ars_elemental-1.18.2-0.4.9.9.jar                  |Ars Elemental                 |ars_elemental                 |1.18.2-0.4.9.9      |DONE      |Manifest: NOSIGNATURE
		canary-mc1.18.2-0.2.4.jar                         |Canary                        |canary                        |0.2.4               |DONE      |Manifest: NOSIGNATURE
		ars_instrumentum-1.18.2-2.5.0.jar                 |Ars Instrumentum              |ars_instrumentum              |2.4.1               |DONE      |Manifest: NOSIGNATURE
		arsarsenal-1.0.5-1.18.2.jar                       |Ars Arsenal                   |arsarsenal                    |1.0.5-{1.18.2}      |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.18.2-1.8.8.jar                        |Vampirism                     |vampirism                     |1.8.8               |DONE      |Manifest: NOSIGNATURE
		VampirismIntegrations-1.18.2-1.7.0-beta.1.jar     |Vampirism Integrations        |vampirism_integrations        |1.7.0-beta.1        |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.18.2-1.0.0.1.jar                     |Werewolves                    |werewolves                    |1.0.0.1             |DONE      |Manifest: NOSIGNATURE
		GodlyVampirism-1.18.1-1.0.4.jar                   |Godly Vampirism               |godly_vampirism               |1.0.4               |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		moredragoneggs-3.1.jar                            |More Dragon Eggs              |moredragoneggs                |3.1                 |DONE      |Manifest: NOSIGNATURE
		lilwings-forge-1.18.2-1.2.4.jar                   |Lil' Wings                    |lilwings                      |1.2.4               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.5.8-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.5.8               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar    |Oh The Biomes You'll Go       |byg                           |1.4                 |DONE      |Manifest: NOSIGNATURE
		Delightful-1.18.2-3.2.1.jar                       |Delightful                    |delightful                    |3.2.1               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		DrinkBeer-Forge1.18.2-3.0.2.jar                   |Drink Beer                    |drinkbeer                     |3.0.2               |DONE      |Manifest: NOSIGNATURE```

**Comment by GordonRamsay20** [comment]
Client only mods are like: NotEnoughAnimations, Rubidium, Occulus, Rubidium Extras.

**Comment by GordonRamsay20** [comment]
latest 1.18 causes no issues, I guess it was fixed
