### ISSUE TITLE
[1.19.2] [0.0.5] Crash: Cannot reduce visibiliy of PUBLIC target method

### ISSUE THREAD

**Issue by Raft08** [AbdElAziz333/Saturn#15]
Hey, First I wanted to give you a big thanks for making these mods they are so useful!

So I've updated to version 0.0.5 and since my game crashes, I don't have deep knowledge into mixins, but after what I understand from the exception your trying to change a method visibility in 'net.minecraft.world.level.biome.Biome' and that causes a crash

I've downgraded to 0.0.4 again just to check and it does not crash.

Thrown exception messages: 
```Mixin apply failed saturn.mixins.json:world.temperature_cache.BiomeMixin -> net.minecraft.world.level.biome.Biome:
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method m_47505_ in
saturn.mixins.json:world.temperature_cache.BiomeMixin cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method m_47505_ in
saturn.mixins.json:world.temperature_cache.BiomeMixin cannot reduce visibiliy of PUBLIC target method

**Comment by Raft08** [comment]
If you need any details other information just ask!

**Comment by Raft08** [comment]
Duplicate of #13 I didn't saw it sorry, I let the issue open for the moment.

**Comment by AbdElAziz333** [comment]
Hi, thanks for your information that helped me a lot, can you please try the new update of [1.19.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.2-0.0.6), i hope you have a good day.

**Comment by AbdElAziz333** [comment]
Can you please use the new update?
[1.18.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.18.2-0.0.6) - [1.19.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.2-0.0.6) - [1.19.3](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.3-0.0.6) - [1.19.4](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.4-0.0.6) - [1.20.1](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.1-0.0.6) - [1.20.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.2-0.0.6)

**Comment by Raft08** [comment]
Yep these did fix my issues! Thanks for the fast fix!
