### ISSUE TITLE
New version has a bug with Wooden Logs

### ISSUE THREAD

**Issue by Smoker120900** [AbdElAziz333/Saturn#18]
forge 1.18.2 - saturn 0.0.6
![imagen_2023-10-12_195950100](https://github.com/AbdElAziz333/Saturn/assets/132844781/aa7786e8-4b53-455f-a8df-cd853fe9c483)

same forge version - saturn 0.0.4 (works as it should)
![image](https://github.com/AbdElAziz333/Saturn/assets/132844781/8c6e08ad-950d-443d-886f-b21564289c43)

**Comment by AbdElAziz333** [comment]
Fixed in the new update, good luck.
