### ISSUE TITLE
[1.16.5] Crashes on startup, states that it needs java 17 when CurseForge indicates it should be java 8 compatible.

### ISSUE THREAD

**Issue by Dasawkem** [AbdElAziz333/Saturn#2]
Hi there, I think title kinda explains the problem pretty well.

`[30Sep2022 19:38:43.550] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 11.0, ASM 9.1 (ASM10_EXPERIMENTAL))`

Essentially, for 1.16.5, I use java 11, so I assumed the mod (labeled java 8 compatible) would be able to be run. However, the game refuses to boot, giving me compatibility error and stating it needs a minimum of java 17. Not sure if this is an issue of mislabeling on CurseForge or an oversight in the mod itself. Hope this helped!

**Comment by AbdElAziz333** [comment]
oo i forgot to change the java version, i will fix this in the new version of 1.16.5.

**Comment by AbdElAziz333** [comment]
fixed it in 0.0.2 version.
