### ISSUE TITLE
(1.20.1) Conflict with Sophisticated Backpacks

### ISSUE THREAD

**Issue by Paulie820** [AbdElAziz333/Saturn#23]
On version 1.20.1-0.0.8, Saturn disables the ability to dye backpacks from the mod Sophisticated backpacks, any existing backpacks default to a light grey color.

![2023-12-09_00 22 59](https://github.com/AbdElAziz333/Saturn/assets/56102321/145c7893-735e-4549-bdf3-a2ecae036a8f)

Normal item dyes do work.

![2023-12-09_00 28 53](https://github.com/AbdElAziz333/Saturn/assets/56102321/02d65148-508c-4235-80e7-fbb877c289cd)

**Comment by DaddySpin** [comment]
It seems to be a thing with modded color maps, because the latest 1.20.1 version also breaks modded biome color maps.

**Comment by Staegrin** [comment]
Disabling one or all the options in the config makes no difference in this bug.
Definitely messing with mod colours  
Mining Gadgets laser and block overlay has disappeared
![2023-12-09_18 09 51](https://github.com/AbdElAziz333/Saturn/assets/8494635/af58bdb1-82ba-43e6-acbb-39bee0bdf40d)
Applied energistics paint ball has lost color
![2023-12-09_18 05 43](https://github.com/AbdElAziz333/Saturn/assets/8494635/ba74536d-63b4-41b2-9645-b9ca2524baed)
Spawn Eggs from various mods have lost colour
![2023-12-09_18 05 43](https://github.com/AbdElAziz333/Saturn/assets/8494635/bf43121f-2ed1-4677-891b-20be5927f8e6)
![2023-12-09_18 07 35](https://github.com/AbdElAziz333/Saturn/assets/8494635/f1573f4b-b649-420a-a184-56757f1d8218)
![2023-12-09_18 07 48](https://github.com/AbdElAziz333/Saturn/assets/8494635/ae2fe8b2-3571-4666-be7c-71fb188587da)
![2023-12-09_18 08 47](https://github.com/AbdElAziz333/Saturn/assets/8494635/ae145515-a32f-4831-8ceb-bd1b1510bde3)
Also blocks and items from various other mods
![2023-12-09_18 06 14](https://github.com/AbdElAziz333/Saturn/assets/8494635/67cb15fe-41d8-4e1a-bc80-05b4252f5583)
![2023-12-09_18 06 22](https://github.com/AbdElAziz333/Saturn/assets/8494635/4aa69a21-dcee-4414-87e3-4358625ed596)
![Uploading 2023-12-09_18.07.14.png…]()
![2023-12-09_18 07 27](https://github.com/AbdElAziz333/Saturn/assets/8494635/ba4ac32e-4934-4cb3-875f-054317f176d3)
![2023-12-09_18 07 41](https://github.com/AbdElAziz333/Saturn/assets/8494635/f159d41b-e6ce-4702-b99e-c28b9b974cba)
![2023-12-09_18 07 54](https://github.com/AbdElAziz333/Saturn/assets/8494635/ca14bbcf-ae24-46d5-ae21-26ddba8e7e6d)
![2023-12-09_18 08 03](https://github.com/AbdElAziz333/Saturn/assets/8494635/98284f53-5822-46d7-af3b-664707ad9742)
![2023-12-09_18 08 30](https://github.com/AbdElAziz333/Saturn/assets/8494635/d2c75ec3-9fd0-4bec-a539-ba58a70eb2ef)
![2023-12-09_18 08 53](https://github.com/AbdElAziz333/Saturn/assets/8494635/fb53da31-91a5-43c7-8212-55b0abe78099)
![2023-12-09_18 09 16](https://github.com/AbdElAziz333/Saturn/assets/8494635/9030ec5a-0c6d-467a-af64-3d0a2e2379f3)
![2023-12-09_18 09 26](https://github.com/AbdElAziz333/Saturn/assets/8494635/8316df7f-0429-4b76-b6ce-835708da8573)
![2023-12-09_18 09 32](https://github.com/AbdElAziz333/Saturn/assets/8494635/d259b330-46be-435e-a993-ce90ca8463ea)

All JAOPCA items
![2023-12-09_18 07 09](https://github.com/AbdElAziz333/Saturn/assets/8494635/75580e51-8e75-4e7f-a7d5-c283c1cd0146)

**Comment by AbdElAziz333** [comment]
can you try please the new update?

**Comment by Staegrin** [comment]
0.0.8 is currently the latest on curseforge. When the newer version is available I'll try

**Comment by Paulie820** [comment]
> can you try please the new update?

Running the latest update has corrected the issue for my case, others will have to verify corrected color maps for other mods. Thank you for the fast response!

**Comment by Staegrin** [comment]
Got the latest version from Modrinth. Indeed all crazy colour loss is fixed in the examples I could find.
