### ISSUE TITLE
[1.18.2-0.0.9] Crash when rendering Glow Squid entity from Upgrade Aquatic in world

### ISSUE THREAD

**Issue by Thombias** [AbdElAziz333/Saturn#24]
I've updated Saturn in my modpack to 0.0.9 from the 0.0.8 version from 10/16/2023 i used to have. Strangely there are two 0.0.8 versions for 1.18.2, i have not tested the 0.0.8 one from 12/9/2023, only the 0.0.9 version was tested.
My game crashed when trying to render the glow squid from the TeamAbnormals Upgrade Aquatic mod, i reverted back to the older 0.0.8 version from 10/16/2023 and it works fine there.

Log output:
![grafik](https://github.com/AbdElAziz333/Saturn/assets/46842890/56e50896-8218-45f6-aacd-fed1fb1dc0c3)
Crash report:
[crash-2023-12-09_15.54.43-client.txt](https://github.com/AbdElAziz333/Saturn/files/13624487/crash-2023-12-09_15.54.43-client.txt)

**Comment by AbdElAziz333** [comment]
can you try please the new update?

**Comment by Thombias** [comment]
I tried both 0.0.10 and 0.1.0 on my 1.18.2 modpack and the crash no longer occurs on both, everything works fine again.
Thank you so much! :)
