### ISSUE TITLE
Broken waypoints with XaerosWorldMap in 1.18.2

### ISSUE THREAD

**Issue by Aer-ink** [AbdElAziz333/Saturn#26]
With the latest release waypoints rendered in the overworld break always showing them on the top left corner of the screen and "growing" at certan camera angles.

useful info I guess
Minecraft 1.18.2
Forge 40.2.14
Saturn 0.0.9
Xaeros Minimap 23.9.1
XaerosWorldMap 1.37.1

![2023-12-09_10 03 16](https://github.com/AbdElAziz333/Saturn/assets/19780430/e94bcac3-cc25-4f8c-ba80-b0b5306ad763)
![2023-12-09_10 03 19](https://github.com/AbdElAziz333/Saturn/assets/19780430/9c5fc035-8f85-469f-a3a7-a7ce5bc54846)
![2023-12-09_10 03 30](https://github.com/AbdElAziz333/Saturn/assets/19780430/13c84231-0c65-4d42-94a4-5993cac85153)

**Comment by uniolelo** [comment]
same issue on 1.20.1

**Comment by AbdElAziz333** [comment]
can you try please the new update?
