### ISSUE TITLE
(1.19.2) (0.0.8) custom cololrs are broken in most recent releases 

### ISSUE THREAD

**Issue by PopSikle23** [AbdElAziz333/Saturn#27]
the green color is missing in leaves in 
![2023-12-09_12 25 58](https://github.com/AbdElAziz333/Saturn/assets/88212115/ac293424-e8a5-4ab0-a5a3-a78c2aab3439)
the mods Ecologics, The Twilight Forest, Sophisticated Backpacks, and Paragliders

**Comment by PopSikle23** [comment]
ANY color in Sophisticated Backpacks and Paragliders

**Comment by PopSikle23** [comment]
0.0.8 has also broken rendering of waypoints from Journey Map

**Comment by PopSikle23** [comment]
it also breaks the rendering of the white outline on FTB Ultimine

**Comment by AbdElAziz333** [comment]
can you try please the new update?
