### ISSUE TITLE
causes my server to crash 

### ISSUE THREAD

**Issue by VenusVesper** [AbdElAziz333/Saturn#31]
Forge: 43.3.0
1.19.2

I have a server with lots of mods around 260 and after some troubleshooting, I realized that Saturn was causing my server to crash. 
I am on the latest update of the mod using version 1.19.2-0.0.8
I really do love this mod since it helps optimize the game so much:)

**Comment by PopSikle23** [comment]
dont put on the server

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by AbdElAziz333** [comment]
Fixed in the new updates.
