### ISSUE TITLE
Create not rendering block placement preview on 0.0.8 for 1.20.1

### ISSUE THREAD

**Issue by yungji** [AbdElAziz333/Saturn#32]
If you're placing a Cog for instance, when looking where you'd like to place another Cog, it normally has a semi translucent model of where the Cog is going to be placed, but with the newest update it doesn't show anymore.

**Comment by Gantros** [comment]
I experienced this as well, also the same thing happened when previewing block placement with Effortless Building.

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by Gantros** [comment]
I gave it a try, so far so good, at least with Effortless Building.

**Comment by AbdElAziz333** [comment]
Fixed in the new updates.
