### ISSUE TITLE
Recent 0.0.8 version crashes/causes an error - MC 1.19.2

### ISSUE THREAD

**Issue by XolfWolf** [AbdElAziz333/Saturn#33]
**Recent 0.0.8 version crashes/causes an error.**

The new version of Saturn causes a _data packs failed validation_ error type and won't allow the creation of new worlds (I didn't try loading a older one).

What I also didn't try was checking if this error still happens even if Saturn is the only mod loaded with forge.

Temp fix = Revert to version 0.0.7

PD: I don't have any data packs.

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by XolfWolf** [comment]
I just try it out.
I updated to 0.1.0 version, works without problem, can make a new world and load a old one.

Thanks for fixing it!
