### ISSUE TITLE
(1.19.2) (0.0.9) saturn does not render create placement preview and also glue overlay

### ISSUE THREAD

**Issue by PopSikle23** [AbdElAziz333/Saturn#34]
![2023-12-09_21 46 26](https://github.com/AbdElAziz333/Saturn/assets/88212115/f02c574f-c480-4d34-9609-99cbeaa7ffff)

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by AbdElAziz333** [comment]
Fixed in the new updates.
