### ISSUE TITLE
most recent saturn versions as of yesterday and today (0.0.8 to 0.1.0) cause crashes upon loading worlds

### ISSUE THREAD

**Issue by poly-1810** [AbdElAziz333/Saturn#35]
[crash-2023-12-10_15.24.02-server.txt](https://github.com/AbdElAziz333/Saturn/files/13629274/crash-2023-12-10_15.24.02-server.txt)
[2023-12-10-1.log](https://github.com/AbdElAziz333/Saturn/files/13629275/2023-12-10-1.log)
here is log and crash report
game version is forge 1.18.2, forge version 40.1.14, modlist should be listed in one of the files given

**Comment by ModernGamingWorld** [comment]
does the samething on 1.19.2, the mod crashes on latest

**Comment by AbdElAziz333** [comment]
This is incompatibility with Radon, please change tickingTrackerLeakFix from true to false.

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by AbdElAziz333** [comment]
This issue should be fixed in the new updates.
