### ISSUE TITLE
[1.19.2] [0.1.3] [Crash] Incompatibility with Radon: Crash on world loading

### ISSUE THREAD

**Issue by Raft08** [AbdElAziz333/Saturn#38]
Game Crash when loading in a world the game crashes

https://mclo.gs/vnzituW

**Comment by ModernGamingWorld** [comment]
I am having this, and noticed the owner has not responded yet. I was wondering when this will be looked at/fixed

**Comment by Raft08** [comment]
I'm sure it will the dev is maybe busy on other projects, atm just stay with version 0.1.2.

**Comment by ModernGamingWorld** [comment]
@Raft08 Removing Radon stop the crash from happening, if you have Radon installed, try removing it

**Comment by Raft08** [comment]
I do have Radon installed but I still would prefer to stay on 0.1.2 until its fixes, but still thanks!

**Comment by Emmulah** [comment]
just commenting to add that I am having this same issue.

**Comment by AbdElAziz333** [comment]
Sorry for the late response, this issue fixed in the new update.

**Comment by Raft08** [comment]
Thanks! I'll test it once I have some time, @ModernGamingWorld could you maybe try ?

**Comment by Raft08** [comment]
I can confirm this has been fixed! Thanks!
