### ISSUE TITLE
ModernFIX 1.20.1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [AbdElAziz333/Saturn#39]
Is it compatible with ModernFIX? 

I once read on Reddit that the mod is not compatible, but since there are no comments from the mod on the curseforge site, I had nowhere to ask how it is here. 

- gpumemleakfix-1.20.1-1.8.jar
- memorysettings-1.20.1-5.4.jar
- ferritecore-6.0.1-forge.jar
- Memory Leak Fix 1.1.5 [forge,1.17+]
- modernfix-forge-5.14.0+mc1.20.1.jar

**Comment by AbdElAziz333** [comment]
Yes, it runs good with ModernFix and the other mods also.
