### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Inf0214** [AbdElAziz333/Saturn#40]
Latest version for 1.18.2 came back with a Trojan in my anti virus. 
Trojan:Script/Wacatac.B!ml
file: C:\Users\user\curseforge\minecraft\Instances\DawnCraft - Echoes of Legends\mods\saturn-mc1.18.2-0.1.5.jar

**Comment by qwerty121123** [comment]
Same thing happened to me with a completely unrelated mod, hoping it's not another Fracturiser situation.

**Comment by AbdElAziz333** [comment]
Saturn is open-source mod, and it doesn't affects the operating system with anything, so I think it happens randomly with random mods, anyway Saturn and my other mods are safe.
