### ISSUE TITLE
"Saturn-mc1.20.4-0.1.3.jar is not a Forge mod"

### ISSUE THREAD

**Issue by Shadowblitz0001** [AbdElAziz333/Saturn#41]
I downloaded only version of Saturn for 1.20.4, but Minecraft refuses to load it, claiming it's not a Forge mod even though Curseforge has it listed as made for Forge.

**Comment by Zefinder** [comment]
Same on Forge 49.0.48

**Comment by AbdElAziz333** [comment]
The issue happens on Forge 49.0.80, update to forge 49.0.50.
