### ISSUE TITLE
[1.18.2] Saturn 0.0.4 conflicts with MemoryLeakFix

### ISSUE THREAD

**Issue by DeshiDesu** [AbdElAziz333/Saturn#8]
Do Saturn and memoryleakfix have the same leak fixes? If true, which mod should I use?

**Mods:**
> Saturn 0.0.4
> MemoryLeakFix 1.0.0 [forge,1.17+]

**Comment by DeshiDesu** [comment]
It seems both mods have the same leak fixes.

**Comment by 5stigma** [comment]
the same problem here. Will it be fixed or any suggestions?

**Comment by DeshiDesu** [comment]
> the same problem here. Will it be fixed or any suggestions?

I don't think the dev will fix it. Just choose memoryleakfix over saturn. Both offer same leak fixes but memoryleakfix has more and better leak fixes.

**Comment by 5stigma** [comment]
I downgraded to  0.0.3 version of Saturn mod and works with Memory Leak Mod
