### ISSUE TITLE
Having issue after updating to the newest version 1.18.2

### ISSUE THREAD

**Issue by Thedarklord0002** [AbdElAziz333/Saturn#9]
[latest.log](https://github.com/AbdElAziz333/Saturn/files/11363113/latest.log)

**Comment by EternalFlam3-14** [comment]
Same issue here, I had to go back to the previous version in order to load my modpack. The log seems to claim that MemoryLeakFix and Saturn are attempting to modify the same thing.

**Comment by Atlantispy** [comment]
Yeah, that seems to be the main conflict, both work independently

**Comment by MaxWasUnavailable** [comment]
Is there a workaround for this?

**Comment by theshadowake** [comment]
https://github.com/AbdElAziz333/Saturn/issues/10

Same issue.

**Comment by AbdElAziz333** [comment]
This issue is fixed in the updated versions.
